export SUPER_QI=${PWD}
export PYTHONPATH=$SUPER_QI/src/python
export PYTHONPATH=$PYTHONPATH/base:$PYTHONPATH/lft:$PYTHONPATH/plot:$PYTHONPATH/qisignal:$PYTHONPATH/utils:$PYTHONPATH
export GOPATH=$SUPER_QI/src/go
