version: '3'

volumes:
  super_qi_data:
    name: ${VOLUME_ID}

services:
  app:
    image: super_qi/os
    container_name: super_qi_os
    volumes:
      - super_qi_data:/usr/share/super_qi/os/data:ro
    entrypoint: bash